
exports.seed = async function(knex) {
  await knex('user_topic').del()
  await knex('topic_paper').del()
  await knex('topics').del()
  await knex('research_papers').del()
  await knex('users').del()
  await knex.raw('TRUNCATE TABLE users RESTART IDENTITY CASCADE')
  await knex.raw('TRUNCATE TABLE topics RESTART IDENTITY CASCADE')
  await knex.raw('TRUNCATE TABLE research_papers RESTART IDENTITY CASCADE')

  await knex('topics').insert([
    { id: 1, name:'Science' },
    { id: 2, name: 'Engineering'  },
    { id: 3, name: 'Statistics' }
  ]);
  await knex('users').insert([
    { id: 1, first_name: 'noel', last_name: 'fernandez', email: 'noelfernandez98@gmail.com' },
    { id: 2, first_name: 'anthony', last_name: 'ng', email: 'newyork.anthonyng@gmail.com' }
  ]);


  await knex('research_papers').insert([
    {
      id: 1, title: "Inhibitory activity of monoacylglycerols on biofilm formation in Aeromonas hydrophila, Streptococcus mutans, Xanthomonas oryzae, and Yersinia enterocolitica\n", abstract: "Biofilm provides a bacterial hiding place by forming a physical barrier and causing physiological changes in cells.The elimination of biofilm is the main goal of hygiene.Chemicals that are inhibitory to biofilm formation have been developed for use in food, personal hygiene products, and medical instruments.Monoacylglycerols are recognized as safe and are used in food as emulsifiers.In this study, the inhibitory activity of monoacylglycerols on bacterial biofilm formation was evaluated systematically with four bacterial strains, Aeromonas hydrophila, Streptococcus mutans, Xanthomonas oryzae, and Yersinia enterocolitica .Monoacylglycerols with two specific lengths of fatty acid moiety, monolaurin and monobehenin, were found to have strong inhibitory activity toward bacterial biofilm formation of S .mutans, X .oryzae, and Y .enterocolitica in a strain specific manner.First, this result suggested that biofilm formation was not inhibited by the detergent characteristics of monoacylglycerols.This suggestion was supported by the inhibitory action of monolaurin on biofilm development but not on the initial cell attachment of Y .enterocolitica in flow cytometric observation.Second, it was also suggested that two distinct response mechanisms to monoacylglycerols existed in bacteria.The existence of these two inhibitory response mechanisms was bacterial strain specific.", url: "https://www.biomedcentral.com/openurl?doi=10.1186/s40064-016-3182-5", week_num: 25
    },
      
    { id: 2, title: 'Tributyltin-mediated hepatic, renal and testicular tissue damage in male Syrian hamster (Mesocricetus auratus): a study on impact of oxidative stress', abstract: "Organotin compounds are a versatile group of organometallic chemicals that are used in a variety of industrial and agricultural applications. Tributyltin (TBT), a common organotin, brings about severe spermatotoxic and organotoxic effects. However, information about the adverse effects of TBT on liver, kidney and testis is scanty. Hence, the present study was undertaken to elucidate the TBT-mediated oxidative stress-induced impairments in these organs. Administration of TBT through oral route at increasing doses of 50, 100 and 150 ppm for 65 days to male Syrian hamsters resulted in drastically decreased activities of antioxidant enzymes superoxide dismutase, catalase and glutathione peroxidase and decreased mean levels of non-enzymatic antioxidants (reduced glutathione, vitamin C, and vitamin E) followed by a dramatic increase in the levels of lipid peroxidation in the liver, kidney and testis as compared to the control animals. Significantly high levels of serum urea, creatinine, uric acid and bilirubin were observed in TBT-treated hamsters. Also, TBT treatment induced drastic histopathological changes in the liver, kidney and testis combined with remarkable changes in serum levels of tissue injury marker enzymes Aspartate transaminases, Alkaline phosphatase and Alanine transaminase. These data affirm that exposure to TBT can lead to oxidative stress-induced damage to liver, kidney and testis. ", url: "https://www.biomedcentral.com/openurl?doi=10.1186/s40064-016-3186-1", week_num: 26},
    { id: 3, title: 'Experimental and numerical study of free-falling streams of particles impacting an inclined surface', abstract: "This paper presents a detailed experimental and numerical analysis of free-falling particle streams impacting a 45° inclined surface of differing materials. The particles used in this study were glass spheres with average diameters of 136 and 342 µm and a density of 2500 kg/m^3. The three mass flow rates considered are 50, 150, and 250 grams per minute (gpm). The effect of wall material on the collision process was also analysed. Special attention was paid to the influence of wall roughness. Therefore, a plate of stainless steel with polished surface, an aluminium sheet, and a Perspex plate with similar properties to those of the rest of the wall sections were used. The experimental data were used to improve and validate a wall collision model in the frame of the Lagrangian approach. A new drag force formula that includes the effects of particle concentration as well as particle Reynolds number was implemented into commercially available codes from CFX4-4 package. It was found that the improved CFD model better predicted the experimental measurements for the particle rebound properties. The rough-wall model in these results showed greater effect on smaller particles than on larger particles. The results also showed that the improved CFD model predicted the velocity changes slightly better than the standard model, and this was confirmed by both the quantitative velocity comparisons and the qualitative concentration plots. Finally, the inclusion of the particle-particle collision was shown to be the dominant factor in providing the dispersion of the particles post collision. Without a sufficient particle-particle collision model, the standard model showed all particles behaving virtually identical, with the main particle stream continuing after the collision process.", url: "http://link.springer.com/openurl/fulltext?id=doi:10.1007/s42757-022-0144-8", week_num: 25},
    { id: 4, title: 'A comprehensive review on exploration and exploitation of offshore geothermal energy', abstract: "World’s ocean has abundance of geothermal energy. Exploration and exploitation of the same is in nascent stage. Several exploration sensors like magnetic, optical, chemical, etc., are towed from ships to sea floor for exploration. Several researches are carried out for drilling these explored hot spots. Once the energy is exploited, the same is transferred to power plant located on land. In this paper, three different types of power plants are discussed namely onshore power plant, offshore power plant, and power generation using the thermoelectric method. This paper narrates the current status of offshore geothermal technology which also includes the technology readiness level of this method. The paper also mentions the parameters which are required for designing of offshore geothermal power plants. Along with the technical aspects of offshore geothermal exploration and exploitation, this paper also talks about the environmental impact of these techniques on marine life. Demonstrative case studies from Indonesia and Italy are presented in this paper. The technical and economic study of the case studies are also briefed. The learnings from these countries may be utilized for the exploration and exploitation of offshore geothermal hotspots of India. Through this paper, it will be easy to understand the technical, financial, and environmental aspects of offshore geothermal technology for developing countries in the field of geothermal.", url: "http://link.springer.com/openurl/fulltext?id=doi:10.1007/s40868-022-00120-3", week_num: 26},
    { id: 5, title: 'A new light on reliability equivalence factors', abstract: "In the reliability theory, the performance of a system can be improved by different methods, such as redundancy and reduction methods. The redundancy method may not be optimal when some restrictions such as volume and weight are crucial. In the reduction method, system reliability is increased by reducing the failure rate of some of its components by a factor $$0<\\rho <1$$ 0 < ρ < 1 which is called the reliability equivalence factor (REF). This article considers a new light on reliability equivalence factors in a coherent system with independent components. A closed form for $$\\rho $$ ρ is obtained when the reduction method is applied on a single component of the system. Based on this, we also define a new measure of component importance. Various numerical illustrative examples are given to support the new results.", url: "http://link.springer.com/openurl/fulltext?id=doi:10.1007/s00184-022-00886-x", week_num: 25},
    { id: 6, title: 'Standardized maximin D- and c-optimal designs for the Poisson–Gamma model', abstract: "The Poisson–Gamma model is obtained as a generalization of the Poisson model, when Gamma distributed block effects are assumed for Poisson count data. We show that optimal designs for estimating linear combinations of the model parameters coincide for the case of known and unknown parameters of the Gamma distribution. To obtain robust designs regarding parameter misspecification we determine standardized maximin D -optimal designs for a binary and a continuous design region. For standardized maximin c -optimality we show that the optimal designs for the Poisson–Gamma and Poisson model are equal and derive optimal designs for both models.", url: "http://link.springer.com/openurl/fulltext?id=doi:10.1007/s00184-022-00890-1", week_num: 26}
  ]);
  await knex('user_topic').insert([
    { user_id: 1, topic_id: 2 },
    { user_id: 2, topic_id: 3 }
  ]);
  await knex('topic_paper').insert([
    { topic_id: 1, paper_id: 1 },
    { topic_id: 1, paper_id: 2 },
    { topic_id: 2, paper_id: 3 },
    { topic_id: 2, paper_id: 4 },
    { topic_id: 3, paper_id: 5 },
    { topic_id: 3, paper_id: 6 }
  ]);
};




